export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  date: string;
  tags: string[];
  problemId?: string;   // links to /problem/[id] if set
  readingTime: number;  // minutes
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "parking-lot-lld-design",
    title: "How to Design a Parking Lot System | LLD Interview Guide",
    description: "Step-by-step breakdown of the Parking Lot LLD problem — entities, class diagram, Strategy pattern for pricing, and what interviewers look for at Amazon, Flipkart.",
    date: "2025-04-01",
    tags: ["lld", "oop", "strategy-pattern", "state-machine"],
    problemId: "parking-lot",
    readingTime: 8,
  },
  {
    slug: "ride-sharing-lld-design",
    title: "How to Design Uber / Ride Sharing | LLD Interview Guide",
    description: "Design a ride sharing system like Uber or Ola. Driver matching, fare calculation, trip state machine, and real interview patterns used at Uber, Ola, Swiggy.",
    date: "2025-04-02",
    tags: ["lld", "state-machine", "factory", "observer"],
    problemId: "ride-sharing",
    readingTime: 9,
  },
  {
    slug: "movie-ticket-booking-lld",
    title: "How to Design BookMyShow (Movie Ticket Booking) | LLD Guide",
    description: "Design a movie ticket booking system with concurrent seat booking, seat locking, pricing strategy, and payment flow — asked at Swiggy, Razorpay, BookMyShow interviews.",
    date: "2025-04-03",
    tags: ["lld", "concurrency", "state-machine", "strategy"],
    problemId: "movie-booking",
    readingTime: 9,
  },
  {
    slug: "elevator-system-lld-design",
    title: "How to Design an Elevator System | LLD Interview Guide",
    description: "Design a multi-elevator control system with optimal assignment, SCAN algorithm, and State pattern. Detailed class breakdown for advanced LLD rounds.",
    date: "2025-04-04",
    tags: ["lld", "state-machine", "command-pattern"],
    problemId: "elevator-system",
    readingTime: 8,
  },
  {
    slug: "url-shortener-lld-design",
    title: "How to Design a URL Shortener (bit.ly) | LLD Interview Guide",
    description: "Design a URL shortening service with Base62 encoding, custom aliases, TTL, and click analytics. Common in Google, Microsoft, and startup LLD rounds.",
    date: "2025-04-05",
    tags: ["lld", "hashing", "analytics", "oop"],
    problemId: "url-shortener",
    readingTime: 7,
  },
  {
    slug: "chat-application-lld-design",
    title: "How to Design a Chat Application (WhatsApp) | LLD Guide",
    description: "Design a WhatsApp-like messaging system — 1-on-1 chats, group chats, message status, Observer pattern for real-time delivery. Common at Slack, Meta, and Zomato.",
    date: "2025-04-06",
    tags: ["lld", "observer", "composite-pattern"],
    problemId: "chat-application",
    readingTime: 8,
  },
  {
    slug: "food-delivery-lld-design",
    title: "How to Design a Food Delivery System (Swiggy/Zomato) | LLD Guide",
    description: "Design Swiggy or Zomato's core system — restaurant browse, order placement, delivery partner assignment, and real-time tracking. Frequently asked at Swiggy interviews.",
    date: "2025-04-07",
    tags: ["lld", "observer", "factory", "strategy"],
    problemId: "food-delivery",
    readingTime: 9,
  },
  {
    slug: "library-management-lld-design",
    title: "How to Design a Library Management System | LLD Interview Guide",
    description: "Design a library system with book borrowing, fine calculation, and notifications. Classic beginner LLD problem asked in entry-level SDE interviews.",
    date: "2025-04-08",
    tags: ["lld", "oop", "observer"],
    problemId: "library-management",
    readingTime: 7,
  },
  {
    slug: "atm-machine-lld-design",
    title: "How to Design an ATM Machine | LLD Interview Guide",
    description: "Design an ATM system with PIN authentication, State pattern, and cash dispensing via Chain of Responsibility. Asked at banks and fintech companies.",
    date: "2025-04-09",
    tags: ["lld", "state-pattern", "chain-of-responsibility"],
    problemId: "atm-machine",
    readingTime: 8,
  },
  {
    slug: "notification-system-lld-design",
    title: "How to Design a Notification System | LLD Interview Guide",
    description: "Design a multi-channel notification service (Email, SMS, Push, In-App) with rate limiting, retry logic, and user preferences. Common at Razorpay, PhonePe.",
    date: "2025-04-10",
    tags: ["lld", "observer", "strategy", "template-method"],
    problemId: "notification-system",
    readingTime: 8,
  },
  {
    slug: "lru-cache-lld-design",
    title: "How to Design an LRU Cache System | LLD Interview Guide",
    description: "Design an LRU cache with O(1) get/set using Doubly Linked List + HashMap, TTL support, and thread safety. Extremely common at FAANG interviews.",
    date: "2025-04-11",
    tags: ["lld", "data-structures", "concurrency"],
    problemId: "cache-system",
    readingTime: 7,
  },
  {
    slug: "payment-gateway-lld-design",
    title: "How to Design a Payment Gateway | LLD Interview Guide",
    description: "Design a payment processing system with idempotency, multiple payment methods, fraud detection hooks, and webhook notifications. Core topic at Razorpay, PayU.",
    date: "2025-04-12",
    tags: ["lld", "strategy", "chain-of-responsibility", "observer"],
    problemId: "payment-gateway",
    readingTime: 10,
  },
  {
    slug: "rate-limiter-lld-design",
    title: "How to Design a Rate Limiter | LLD Interview Guide",
    description: "Design a rate limiter with Token Bucket, Sliding Window, and Fixed Window algorithms. Strategy pattern, distributed state, and burst handling explained.",
    date: "2025-04-13",
    tags: ["lld", "strategy", "distributed-systems"],
    problemId: "rate-limiter",
    readingTime: 8,
  },
  {
    slug: "expense-splitter-lld-design",
    title: "How to Design Splitwise (Expense Splitter) | LLD Guide",
    description: "Design a Splitwise-like app with equal, exact, and percentage splits, balance tracking, and debt simplification algorithm. Asked at fintech SDE interviews.",
    date: "2025-04-14",
    tags: ["lld", "oop", "graph-algorithm", "strategy"],
    problemId: "expense-splitter",
    readingTime: 8,
  },
  {
    slug: "social-media-feed-lld",
    title: "How to Design a Social Media Feed (Twitter/Instagram) | LLD Guide",
    description: "Design a Twitter or Instagram feed with posts, follows, fan-out strategies, trending hashtags, and notification system. Advanced LLD for senior SDE rounds.",
    date: "2025-04-15",
    tags: ["lld", "observer", "fan-out", "strategy"],
    problemId: "social-media-feed",
    readingTime: 9,
  },
  {
    slug: "job-scheduler-lld-design",
    title: "How to Design a Distributed Job Scheduler | LLD Interview Guide",
    description: "Design a job scheduling system with cron support, priority queues, retry with backoff, and distributed workers. Senior-level LLD problem at Amazon, Flipkart.",
    date: "2025-04-16",
    tags: ["lld", "distributed-systems", "command-pattern", "observer"],
    problemId: "job-scheduler",
    readingTime: 10,
  },
  {
    slug: "hotel-booking-lld-design",
    title: "How to Design a Hotel Booking System (OYO) | LLD Guide",
    description: "Design a hotel booking platform with room availability, dynamic pricing, cancellation policy, and concurrent reservation safety. Common in product-based SDE rounds.",
    date: "2025-04-17",
    tags: ["lld", "strategy", "template-method", "state-machine"],
    problemId: "hotel-booking",
    readingTime: 8,
  },
  {
    slug: "inventory-management-lld-design",
    title: "How to Design an Inventory Management System | LLD Guide",
    description: "Design a warehouse inventory system with stock reservation, audit trail, multi-warehouse transfers, and auto reorder. Asked at Amazon, Flipkart SDE interviews.",
    date: "2025-04-18",
    tags: ["lld", "command-pattern", "observer"],
    problemId: "inventory-management",
    readingTime: 8,
  },
  {
    slug: "event-ticketing-lld-design",
    title: "How to Design an Event Ticketing System (Ticketmaster) | LLD",
    description: "Design a high-concurrency ticket booking system with seat holds, waiting lists, dynamic pricing, and overselling prevention. Advanced LLD for senior engineers.",
    date: "2025-04-19",
    tags: ["lld", "concurrency", "observer", "strategy"],
    problemId: "event-booking",
    readingTime: 9,
  },
  {
    slug: "logger-framework-lld-design",
    title: "How to Design a Logging Framework | LLD Interview Guide",
    description: "Design a flexible logging system with multiple handlers, formatters, and log levels. Chain of Responsibility, Singleton, and Observer patterns explained.",
    date: "2025-04-20",
    tags: ["lld", "chain-of-responsibility", "singleton", "observer"],
    problemId: "logger-system",
    readingTime: 7,
  },
  // Bonus: concept posts that rank for keyword clusters
  {
    slug: "solid-principles-lld-interview",
    title: "SOLID Principles Explained with LLD Examples | Interview Guide",
    description: "Understand SOLID principles with real low-level design examples. SRP, OCP, LSP, ISP, DIP — how interviewers test these in LLD rounds at top companies.",
    date: "2025-04-21",
    tags: ["solid", "oop", "lld", "interview"],
    readingTime: 10,
  },
  {
    slug: "design-patterns-lld-interview",
    title: "Top 10 Design Patterns for LLD Interviews | Complete Guide",
    description: "Strategy, Observer, Factory, State, Command, Decorator — the 10 design patterns that appear in 90% of LLD interview questions. With real examples.",
    date: "2025-04-22",
    tags: ["design-patterns", "lld", "interview"],
    readingTime: 12,
  },
  {
    slug: "how-to-crack-lld-interview",
    title: "How to Crack the LLD Interview Round | Complete Strategy Guide",
    description: "Step-by-step strategy to crack the Low Level Design interview round at Amazon, Flipkart, Swiggy, and other top companies. Requirements gathering, entity design, class diagram.",
    date: "2025-04-23",
    tags: ["lld", "interview-tips", "career"],
    readingTime: 11,
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug);
}
